# Generated by Django 4.1 on 2022-10-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contenttype",
            name="tags",
            field=models.CharField(
                choices=[("PAGE", "Page"), ("ARTICLE", "Article"), ("STORY", "Story")],
                default="Page",
                max_length=10,
            ),
        ),
    ]
