# Generated by Django 4.1 on 2022-10-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_alter_contenttype_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="contenttype",
            name="page_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
