# Generated by Django 4.1 on 2022-10-07 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0003_contenttype_page_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="contenttype",
            name="author",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
