# Generated by Django 4.1 on 2022-10-09 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0004_contenttype_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PAGE", "Page"),
                            ("ARTICLE", "Article"),
                            ("STORY", "Story"),
                        ],
                        default="Page",
                        max_length=10,
                    ),
                ),
                ("page_name", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100, unique=True)),
                ("content", models.TextField()),
                ("active", models.BooleanField(default=False)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContentImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images")),
                (
                    "cb",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.content",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="contenttypeimage",
            name="cb",
        ),
        migrations.DeleteModel(
            name="ContentType",
        ),
        migrations.DeleteModel(
            name="ContentTypeImage",
        ),
    ]
