# Generated by Django 4.1 on 2022-10-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_content_contentimage_remove_contenttypeimage_cb_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="page_name",
        ),
        migrations.AddField(
            model_name="content",
            name="name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
